name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build Docker image
      run: |
        docker build -t k8s-demo-app:latest .
        echo "Docker image built successfully"

    - name: Create namespace if not exists
      run: |
        kubectl get namespace scd-project || kubectl apply -f k8s/namespace.yaml
        echo "Namespace created or already exists"

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/pvc.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/mongodb-deployment.yaml
        kubectl apply -f k8s/mongodb-service.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        echo "Deployed to Minikube"

    - name: Wait for deployments to be ready
      run: |
        kubectl -n scd-project rollout status deployment/k8s-demo-app
        kubectl -n scd-project rollout status deployment/mongo
        echo "Deployments are ready"

    - name: Show application URL
      run: |
        echo "Your application is available at:"
        minikube service -n scd-project k8s-demo-service --url 